---
engines:
  fixme:
    enabled: true
    exclude_fingerprints:
    - f4fdfaaab3dfb8670a495ee1f2b9e20e
  pmd:
    enabled: true
    channel: "beta"
    exclude_fingerprints:
    - d58713d342d24b2a02c9b3d13755d65d
ratings:
  paths:
  - "**.java"
exclude_paths: []
