version: '{build}'
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: choco install -i maven
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean install -DskipTests=true
test_script:
  - mvn clean test -DstorageEngine=InMemory
  - mvn clean test -DstorageEngine=MapDB
cache:
  - C:\Users\appveyor\.m2